### ISSUE TITLE
EventJournal adapters sometimes are not registered

### ISSUE THREAD

**Issue by bwehrle** [vlingo/vlingo-lattice#1]
In my example code, I have a single entity (shopping Cart) that has 3 events.  On every 5th run or so the service spits out this error message.  In the code, the regististration of the "CreatedEvent" adapter is made very clearly.  There appears to be some kind of race condition that can cause the registration to not be considered and the "recovery error" to be logged.  In my example this does not provable affect the actor, but it certainly should be investigated.

You can see this in my fork of the examples, using the branch feature/event-sourced-example
https://github.com/bwehrle/vlingo-examples/commit/dbb629c7b3fc9a57f676b39d6ac4a4702e65f32f
Please run this in a loop until you see the issue:

     mvn test -pl vlingo-ecommerce

To wait for this to happen you can run:

    while true ; do mvn test -pl vlingo-ecommerce | grep Exception ; sleep 0.5 ; done & 

> vlingo/actors: Message#deliver(): Exception: Stream not recovered for: CartEntity(cartEvents) because: Adapter not registrered for: io.vlingo.examples.ecommerce.model.CartEvents$CreatedEvent for Actor: Actor[type=CartEntity address=Address[id=135, name=cart-135]] sending: start()
> vlingo/actors: io.vlingo.symbio.store.StorageException: Stream not recovered for: CartEntity(cartEvents) because: Adapter not registrered for: io.vlingo.examples.ecommerce.model.CartEvents$CreatedEvent
> 	at io.vlingo.lattice.model.sourcing.Sourced.lambda$restore$7(Sourced.java:271)
> 	at io.vlingo.common.BasicCompletes$BasicActiveState.handleException(BasicCompletes.java:501)
> 	at io.vlingo.common.BasicCompletes$BasicActiveState.exceptionAction(BasicCompletes.java:490)
> 	at io.vlingo.common.BasicCompletes.recoverFrom(BasicCompletes.java:148)

**Comment by VaughnVernon** [comment]
@bwehrle Thanks! Would you mind attempting to debug this via vlingo-actors? It is possible that the following is involved:

0. Sourced::apply(???)
1. Actors::stowMessages()
2. appendResultedIn()/appendAllResultedIn()
3. Actors::disperseStowedMessages()

It's possible that the stowed messages are being dispatched prematurely or out of order.

**Comment by VaughnVernon** [comment]
@bwehrle Would you please pull version `0.7.9` just released and let me know whether this Issue has been fixed? The binary artifacts are *_on Bintray only_*:

https://bintray.com/vlingo/vlingo-platform-java

```xml
  <repositories>
    <repository>
      <id>jcenter</id>
      <url>https://jcenter.bintray.com/</url>
    </repository>
  </repositories>
```

I think that the problem was with `CompletesEventually` pooled actors were being selected for various requests and could complete out of order, which would cause `restore()` and `apply()` to fail under some conditions. Now a given actor that requests a eventual completion should see each of the completions occur in the order in which they were requested. If this doesn't fix your issue then I will need a complete example that causes the issue.

**Comment by bwehrle** [comment]
Hi,

I´m still seeing this issue, and it happened pretty quickly, after a  few
runs.  I moved the vlingo pom dependencies to 0.7.9 in my fork for my
example project..
I think if you pull the new code this should repo again for you quickly.
I  didn´t try this with the other examples, but I assume you can repo with
them as well doing the same type of repetitive test run.

Regards,
Brian

**Comment by bwehrle** [comment]
Based on our conversation regarding how entity state should be managed in actor and constructors, I'm going to change my implementation as I suspect that using the apply() in the entity constructor might be related to this problem.

**Comment by bwehrle** [comment]
I think this issue is resolved; after making the  recommended changes I cannot get this to repo (I am  hitting other different issues). So I will close this for now.
